# Generated by Django 3.0.8 on 2020-07-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(default='100', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='firstname',
            field=models.CharField(default='Matti Meikäläinen', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='lastname',
            field=models.CharField(default='Meikäläinen', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='0401298746', max_length=15),
            preserve_default=False,
        ),
    ]
