# Generated by Django 3.0.8 on 2020-07-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeAPI', '0002_auto_20200726_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=3)),
                ('companyname', models.CharField(max_length=50)),
                ('contactname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=3)),
                ('productname', models.CharField(max_length=50)),
                ('quantity_per_unit', models.CharField(max_length=50)),
                ('units_in_stock', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
